name: Create Release
on:
  push:
    tags:
      - '*'
jobs:
  release_zip_file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: ZIP Dir
        run: |
          cd ${{ github.workspace }}/custom_components/x96
          zip x96-${{ github.ref_name }}.zip -r ./

      - name: Create Release
        uses: softprops/action-gh-release@v2.0.9
        env:
          GITHUB_TOKEN: ${{ secrets.x96max_token }}
        with:
          files: ${{ github.workspace }}/custom_components/x96/x96-${{ github.ref_name }}.zip

