name: Create Release
on:
  push:
    tags:
      - '*'
jobs:
  release_zip_file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: ZIP Dir
        run: |
          cd ${{ github.workspace }}
          zip x96-${{ github.ref_name }}.zip -r ./

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.x96max_token }}
        with:
          files: ${{ github.workspace }}/x96-${{ github.ref_name }}.zip

